### ISSUE TITLE
schedule November 2014 meeting

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#1]
cc: @dmk246 @oakes @hmig @pfulton @burnified @weallhave24hrs

**Comment by chadwhitacre** [comment]
@oakes will be at the Conj 19-22. The week after is Thanksgiving, so that's out. [Looks like](https://twitter.com/refreshpitt) Refresh hasn't been scheduled yet.

How about Wednesday the 12th (week from today) or Monday the 17th?

What should we do? I kinda liked the live group coding format. I like actual coding on real projects. Is that a good way to help beginners get involved by seeing what "real programming" looks like?

**Comment by chadwhitacre** [comment]
We'll have to check with Blue Canary for room availability.

P.S. They do actually have a $50 fee to rent the back room for the evening. They waived it the first time for us since we're just getting started. We shouldn't impose on them too much if we can help it.

**Comment by pfulton** [comment]
The next Refresh is on Tuesday, November 18 at 6:30 at Left Field Meeting Space ;-)

**Comment by burnified** [comment]
I'm good for the 12 (+ the 18, @pfulton) :)

**Comment by chadwhitacre** [comment]
@pfulton Cool. :-)

So maybe let's go for Wednesday the 12th to minimize conflict?

**Comment by oakes** [comment]
I'm good for the 12th as well.

**Comment by hmig** [comment]
Looks good for me as well. :)

**Comment by chadwhitacre** [comment]
Alright, I think we have a quorum! Wednesday, November 12th it is! 7-8pm.

![photo on 11-5-14 at 5 36 pm](https://cloud.githubusercontent.com/assets/134455/4927546/6a84d5d6-653c-11e4-8100-a8154a624a3b.jpg)

**Comment by chadwhitacre** [comment]
What format should we use for the meeting? Can we do more live coding, either as a group or paired up? :-)

**Comment by burnified** [comment]
# 11/12/14 Meeting Notes

We worked on the Blue Canary Coffehouse, which is built on Wordpress.

## Work Completed on 11/12/14
- Get rid of Google+
- nav background fixed
- made/uploaded new logo

## Feature List
- Event Calendar (request events)
- Menu
- Adding

**Comment by chadwhitacre** [comment]
Yeah Mark! Thanks for taking notes! :D

**Comment by chadwhitacre** [comment]
I guess let's close the books on this? Do we want to reticket the feature list for Blue Canary's website? We could ticket them in this repo and use a "Blue Canary" label? Or we could just let it ride for now and dig up this ticket the next time we get around to Blue Canary?
