### ISSUE TITLE
Exploding Kittens @ the coffee house

### ISSUE THREAD

**Issue by hmig** [Ambridge/ambridge.cc#10]
Hi Everyone,

I have a favor to ask...

Please like [this video](https://youtu.be/Ddks8XVhy6A) on YouTube to help us bring Exploding Kittens to the Blue Canary Coffee house.

Thanks!

**Comment by chadwhitacre** [comment]
Done! :-)

**Comment by hmig** [comment]
TY!

iPhone. iAutocorrect. iSiri. iSorry.
