### ISSUE TITLE
Brainstorm Sponsors

### ISSUE THREAD

**Issue by seantosz** [Ambridge/ambridge.cc#3]

**Comment by seantosz** [comment]
[Ni's Wok](http://www.niswok.com/)

**Comment by seantosz** [comment]
[Franks Pizza](http://franks-pizzeria.com/)

**Comment by seantosz** [comment]
[Ambridge Connection](http://www.ambridgeconnection.com)

**Comment by seantosz** [comment]
[Ambridge Regional](http://www.ambridgeregional.com/)

**Comment by chadwhitacre** [comment]
Ftr the idea here (ht @hmig) was that we would find local business sponsors for each meeting. The sponsor would pay the $50 that we owe Blue Canary, and we would spend the hour working on their website. See https://github.com/Ambridge/ambridge.cc/issues/1#issuecomment-62824258 for our first  example.

**Comment by chadwhitacre** [comment]
I talked to Ivan at the bus stop this morning. His sister Sandy manages the Ni's Wok website. Maybe she wants to join the Club? :-)

**Comment by chadwhitacre** [comment]
BlueCanary is letting us use the room for free! :heart_eyes: Thank you, Blue Canary! :bird: :blue_heart:   Buy drinks while you're there, everyone! :coffee:
