### ISSUE TITLE
December 2014

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#4]
Second Wednesday would be Dec 10. Sound good to everyone?

**Comment by pfulton** [comment]
Right now, this works for me.

**Comment by burnified** [comment]
I won't be able to make it to this Wednesday's meetup, guys. :(

**Comment by pfulton** [comment]
Just found out that I can't make it on Wednesday, either. Have fun, y'all!

**Comment by chadwhitacre** [comment]
@burnified @pfulton Oh no! Ah, well. Happy holidays to you both! :-)

**Comment by seantosz** [comment]
I will be there.

**Comment by hmig** [comment]
Sorry, folks. Count me out tonight.

**Comment by chadwhitacre** [comment]
Okay! Working on zanafest.com tonight. TODO:
- [x] clear out old info from homepage
- [x] add Youth Talent event info to homepage (flyer and registration PDF)
- [ ] ~~set up a registration and payment form for the Youth Talent event~~ reticketed as #5

**Comment by chadwhitacre** [comment]
Here's teh poster:

![img_1751441411746](https://cloud.githubusercontent.com/assets/134455/5386996/0234a454-80a1-11e4-9b58-c802ad58029b.jpeg)

**Comment by chadwhitacre** [comment]
Got the homepage cleared out and the poster+PDF done at the meeting. Will implement online registration/payment later.

**Comment by chadwhitacre** [comment]
Reticketed: #5.

**Comment by chadwhitacre** [comment]
Next meeting is January 14th. Site updated in 2141aaf3f0c93e43906a26451fa877a68e790532 and reticketed as #6.

**Comment by chadwhitacre** [comment]
Huzzah! :-)
