### ISSUE TITLE
set up a registration and payment form for the Youth Talent event

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#5]
This for the ZanaFest website. Reticketed from #4.

**Comment by chadwhitacre** [comment]
Thinking either:
- [Google forms + PayPal](http://www.lifehacker.com.au/2013/10/easily-connect-google-forms-to-paypal/)
- [Wufoo + Stripe](http://www.wufoo.com/payments/stripe/)

**Comment by seantosz** [comment]
wufoo + Stripe looks nicer to me.  People won't need a PayPal log in to make donations.

**Comment by chadwhitacre** [comment]
@seantosz Yeah, costs money, though. $29/mo to use the wufoo/stripe integration. :-/

**Comment by chadwhitacre** [comment]
http://www.wufoo.com/pricing/

**Comment by seantosz** [comment]
You're right with intermittent payments monthly fee won't be worth it.  I think square has online modules for websites but I don't know about its functionality.

**Comment by chadwhitacre** [comment]
This got done at some point. We ended up using a freebie service: http://www.crazychro.me/gform/.
