### ISSUE TITLE
January 2015

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#6]
December 2014: #4.

**Comment by chadwhitacre** [comment]
Anyone able to make it tonight? What should we work on?

One idea: https://github.com/gratipay/gratipay.com/pull/3063. I want to invert the media queries on Gratipay from `max-width` to `min-width`, while leaving the site looking the same from the outside (for now).

**Comment by burnified** [comment]
Oh, crap! I'm tied up all week. I would love to help out with Gratipay's transition to mobile-first, though! :+1:  Hit me up sometime!

**Comment by chadwhitacre** [comment]
@burnified Thanks! We'll have to see how far we get tonight. :-)

**Comment by pfulton** [comment]
'doh. completely forgot about this. I need to add these to my calendar when I get the GH notifications...

**Comment by chadwhitacre** [comment]
@pfulton No worries! Second Wednesday, if you want to set up a recurring event. :-)

**Comment by hmig** [comment]
Super sick. Count me out tonight.

iPhone. iAutocorrect. iSiri. iSorry.

**Comment by whit537** [comment]
Video one is up! https://www.youtube.com/watch?v=FDOLExNiBnY

Uploading number two now. :)

**Comment by chadwhitacre** [comment]
@hmig Oh no! Get well. :-(

**Comment by chadwhitacre** [comment]
Here with @laholley and @dmk246. Catching up on @laholley's recent Hadoop and Oracle trainings.

**Comment by chadwhitacre** [comment]
We went through a Java [hello world](http://www.thegeekstuff.com/2010/02/java-hello-world-example-how-to-write-and-execute-java-program-on-unix-os/).

**Comment by chadwhitacre** [comment]
Okay! That's a wrap. :-)

Feb 11 reticketed as #7, though @laholley thinks we should meet more frequently.

**Comment by chadwhitacre** [comment]
``` java
class GreetingsProgram {
    public static void main(String[] args)
    {
        System.out.println("Greetings, program!");
    }
}
```
