### ISSUE TITLE
February 11, 2015

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#7]
[Jan 2015](https://github.com/Ambridge/ambridge.cc/issues/6)

**Comment by chadwhitacre** [comment]
Hey all, next meeting is coming up next week! Anyone around for it? :)

**Comment by hmig** [comment]
It looks like I'm available this week.

**Comment by pfulton** [comment]
I might be able to make it. It'll be a game-time decision, though ;-)

**Comment by chadwhitacre** [comment]
Sweet! I heard from a dad in Sewickley who might bring his kid. Sounds like Larissa is a probably as well.

**Comment by chadwhitacre** [comment]
Okay! Sitting here with @liamwhite about to set up an Inkscape dev environment. @laholley and Karen (who hacks with http://pixologic.com/sculptris/) and @kaguillera are at the table as well. A couple kids hacking with Scratch in the other room.

**Comment by chadwhitacre** [comment]
cc: @kromestan :dancer:

**Comment by chadwhitacre** [comment]
Okay! Here's what we accomplished tonight:
- installed `pkg-config`, `libpng`, `pixman`, and `cairo` from source :dancer: 
- made a bunny! :rabbit:
- @kromestan registered for GitHub :beers: 

I told @laholley that if she wants to meet more often then she should make tickets for when she wants to meet, and rope in @dmk246.

**Comment by chadwhitacre** [comment]
March 11 ticketed as #8.

**Comment by chadwhitacre** [comment]
FTR, @hmig showed up as well.
