### ISSUE TITLE
March 11, 2015

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#8]

**Comment by chadwhitacre** [comment]
Anyone up for a meeting tomorrow night? :)

cc: @kromestan @laholley @liamwhite @kaguillera

**Comment by pfulton** [comment]
Can't make it tonight, but will definitely try next month!

**Comment by laholley** [comment]
Karyn and I will be there!

**Comment by chadwhitacre** [comment]
@laholley Yay! @kaguillera is here now, he'll be around tonight. :-)

@pfulton One of these months. :-)

**Comment by chadwhitacre** [comment]
Live ticket! :dancer: 

@laholley and @kromestan just rolled in. @kaguillera holding down the fort, @lolgaming is here as well. Might look at some Blender and/or Maya tonight.

**Comment by chadwhitacre** [comment]
@hmig is in the other room. Ping, @hmig, I guess. :-)

**Comment by chadwhitacre** [comment]
A wild @dmk246 appears! :bear:

**Comment by chadwhitacre** [comment]
GAMES!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by chadwhitacre** [comment]
Winding down here. We did a 20 minute 101 on GitHub for @kromestan @laholley, then @kromestan introduced us to Sculptris. We ended up talking about game dev, and we decided to make a game together as a club. It's called Geede5 (pronounced "geode five"&mdash;don't be fooled! :grin:). Here's the repo: https://github.com/Ambridge/Geede5.

**Comment by chadwhitacre** [comment]
:dancer:

**Comment by LOLGAMING** [comment]
Asome
