### ISSUE TITLE
April 8, 2015

### ISSUE THREAD

**Issue by chadwhitacre** [Ambridge/ambridge.cc#9]
[March 11](https://github.com/Ambridge/ambridge.cc/issues/8)

**Comment by chadwhitacre** [comment]
Anyone up for a meeting on Wednesday?

**Comment by laholley** [comment]
I don't think I will make it :-(  I am in Cleveland for an interview for
the day.  I may make it back in time though.

**Comment by burnified** [comment]
Sorry guys, I have family up tonight from out of town. Have fun, though!

**Comment by chadwhitacre** [comment]
Sounds like @kaguillera is staying through, and @liamwhite may make it as well.

**Comment by hmig** [comment]
Count me out. Not feeling well. :(

**Comment by chadwhitacre** [comment]
:cry: :chicken: :ramen:

**Comment by chadwhitacre** [comment]
@LOLGAMING HAS ARRIVED. :sunglasses:

**Comment by chadwhitacre** [comment]
Okay! Getting started. 

"Inkscape's test suite runs in 10 seconds."
"That's either really optimized, or really small."
"It's really small."

:tangerine:

**Comment by chadwhitacre** [comment]
We're going to work on https://github.com/Ambridge/Geede5.

**Comment by chadwhitacre** [comment]
Let's look at https://github.com/Ambridge/Geede5/issues.

**Comment by chadwhitacre** [comment]
Erm ... https://github.com/Ambridge/Geede5/issues/2. :-)

**Comment by chadwhitacre** [comment]
Huzzah! We worked on Geede5 and closed four issues ... #2 #3 #4 and #5. Yessss.

![screen shot 2015-04-08 at 8 10 27 pm](https://cloud.githubusercontent.com/assets/134455/7058115/655a7d82-de2b-11e4-80ee-f50245fac86c.png)

**Comment by chadwhitacre** [comment]
lol

Site bumped in a661408f5230712bf5ec72566641722235db6b48.

See yinz next month! :dancer:
